### ISSUE TITLE
Login page와 Home page를 결합시켰을 때 문제가 발생함

### ISSUE THREAD

**Issue by kdw8573** [hjcdg1/swpp_cjlk#10]
기존의 코드에서는 Home page에서 state가 인식을 하지 못했다. 문제를 분석한 결과 container는 import를 계층 단위 page가 아니여야 작동을 한다. container를 가진 component를 import할때는 component 디렉토리에 있는 것을 import 하는게 아니라 container 디렉토리에 있는 것을 import해야 한다.

**Comment by PrE-Ren** [comment]
Page가 최상위 단위여서 일어나는 문제로 Organism 아래쪽 단위를 사용해야 하며, 이 과정에서 단위가 부족하면 atom이 atom을 import하거나 molecule이 molecule을 import하는등으로 처리하기로 함.
