### ISSUE TITLE
신고 모델과 운영자의 처리 관련

### ISSUE THREAD

**Issue by PrE-Ren** [hjcdg1/swpp_cjlk#116]
팀원들과의 토의를 통해서 운영자의 역할 결정

운영자는 운영자 페이지에서 다음 동작을 할 수 있다.

기본적으로 운영자는 신고를 처리/기각 할 수 있으며 처리 시 해당 유저에게 벌점이 부여되며, 기각 시 해당 유저에게 벌점이 부여되지 않는다.

단, 유저는 운영자에게 항의를 할 수 있으며 이 경우 운영자는 이미 처리된 신고를 되돌릴 수 있다. 
신고가 되돌려지면 유저에게 부여된 벌점이 회수된다.

문제점이나 추가적으로 토의할 사항이 있다면 댓글 바람.

**Comment by ComputerMath** [comment]
https://github.com/hjcdg1/swpp_cjlk/pull/117
해결했습니다
