### ISSUE TITLE
이거 무슨 용도의 클래스인가요?

### ISSUE THREAD

**Issue by hjcdg1** [hjcdg1/swpp_cjlk#18]
https://github.com/hjcdg1/swpp_cjlk/blob/c272982aa8988864d3992a84c5bad75e2f175fae/back/snu_moyeo/permissions.py#L15

접근 권한을 설정하는 것 같긴 한데 자세히는 이해 안 가서 설명좀 부탁드리겠습니다.

**Comment by ComputerMath** [comment]
각 meeting에 대해서, meeting의 수정 및 삭제와 같은 권한은 
meeting을 개최한 leader만 할 수 있습니다.

다만 superuser의 경우는 모든 권한이 있습니다

**Comment by ComputerMath** [comment]
문제 해결 closed 
(tests.py를 통해 테스트도 완료)
