### ISSUE TITLE
Back-end  implementation about getting meeting lists

### ISSUE THREAD

**Issue by hjcdg1** [hjcdg1/swpp_cjlk#35]
현재는 미팅 목록을 가져오는 URL(/meetinglist)과 View 클래스(MeetingList)가 하나만 있음. 하지만 다음과 같이 종류를 나눠서 따로따로 URL과 View 클래스를 만드는 것이 좋아 보임.

1. 마감 임박 미팅 목록 (Home 페이지에서 가져올 것)
2. 전체 미팅 목록 (Home 페이지에서 가져올 것)
3. n번째 페이지에서 보여줄 미팅 목록 (List 페이지에서 가져올 것)

<1번 보충 설명>
URL : "meetinglist/impending"
VIEW 클래스 : 전체 미팅들의 리스트를 가져온 뒤(list(Meeting.objects.all())), due 필드에 따라 오름차순 정렬한 후 제한된 개수만 queryset 변수에 설정해주면 됨(500개가 있다고 해서 Home 페이지에 500개를 다 띄울 건 아님. 만약 10개만 띄울 거라면, 리스트를 인덱스 9까지만 잘라내어 queryset 변수에 설정해주면 됨.)

<2번 보충 설명>
URL : "meetinglist/all"
VIEW 클래스 : 전체 미팅들의 리스트를 가져온 뒤(list(Meeting.objects.all())), 제한된 개수만 queryset 변수에 설정해주면 됨. Meeting 모델의 ordering이 -created로 설정되어 있기 때문에 다시 정렬할 필요는 없음.

<3번 보충 설명>
1번과 2번은 매우 간단한데, 3번은 약간 복잡할 수 있음.

URL : "meetinglist/음식배달/page/<int:n>", "meetinglist/택시합승/page/<int:n>", "meetinglist/공동구매/page/<int:n>", "meetinglist/스터디/page/<int:n>", "meetinglist/운동/page/<int:n>", "meetinglist/미팅/page/<int:n>", . . .
→ "meetinglist/A/page/k"는A 타입의 미팅 목록에서 k번째 페이지를 보여달라는 것을 의미함.

VIEW 클래스 : 한 페이지에 10개씩 나열하여 보여준다고 해보자(그러면 페이지의 총 개수는 Ceiling function of [해당 타입의 미팅 개수 ÷ 10]이 됨. ). 그러면 먼저 1번이나 2번처럼 똑같이 오브젝트를 가져온 후 Meeting의 type으로 필터링하여 시간 순으로 정렬된 AAA 타입의 미팅 리스트 L을 얻어내고, L[10*(n-1), 10*n-1]을 queryset으로 설정해주면 됨.

자세히 읽어보고, 그래도 이해가 안 갈 수 있을 만한 내용이니 궁금한 게 있다면 댓글로 질문해주세요!!

**Comment by hjcdg1** [comment]
Queryset(Meeting.objects.all() 반환값의 타입) 관련 API

Slicing(잘라내기), Filtering(조건에 맞는 것들로 다시 queryset 구성), Ordering(정렬) . . .

→ https://docs.djangoproject.com/en/2.2/ref/models/querysets/

**Comment by hjcdg1** [comment]
+ 추가 (In MyPage)

1. 내가 만든 모임
URL : "meetinglist/lead"
VIEW : Front에서 보내준 유저의 ID 값에 대응되는 유저 객체의 lead_meeting 필드에서 내가 만든 미팅의 목록들을 가져옴(SnuUser.objects.get(pk=id)). 그리고 이걸 queryset 변수에 설정해주면 됨. (정렬 혹은 제한된 개수에 대한 이슈는 추후 논의 필요)

2. 내가 참여 중인 모임
URL : "meetinglist/join"
VIEW : Front에서 보내준 유저의 ID 값을 user_id 값으로 가지는 Participate 객체들을 모두 찾아서 내가 참여한(혹은 참여했던) 미팅들의 목록을 가져온다. 그리고 나서 그 중에서 state 필드 값이 0 혹은 1 혹은 2인 것들을 가져와서 queryset 변수에 설정해주면 됨. (정렬 혹은 제한된 개수에 대한 이슈는 추후 논의 필요)

3. 내가 참여했던 모임
URL : "meetinglist/history"
VIEW : Front에서 보내준 유저의 ID 값을 user_id 값으로 가지는 Participate 객체들을 모두 찾아서 내가 참여한(혹은 참여했던) 미팅들의 목록을 가져온다. 그리고 나서 그 중에서 state 필드 값이 3인 것들을 가져와서 queryset 변수에 설정해주면 됨. (정렬 혹은 제한된 개수에 대한 이슈는 추후 논의 필요)

**Comment by ComputerMath** [comment]
https://github.com/hjcdg1/swpp_cjlk/issues/48
에서 구현 완료를 했으니 해당 이슈는 닫습니다
