### ISSUE TITLE
backend에서 member 변수에 관한 문제

### ISSUE THREAD

**Issue by kdw8573** [hjcdg1/swpp_cjlk#43]
member가 최대 인원을 넘어가지 않도록 만드는 조건이 보이지 않음. 추후 추가 바람.

**Comment by PrE-Ren** [comment]
힘들면 프론트쪽에서 인원수 차면 참여 버튼 안보이게 해도 될듯?

**Comment by hjcdg1** [comment]
그래도 백엔드에서 처리해주는 게 간편하지 않을까

**Comment by ComputerMath** [comment]
https://github.com/hjcdg1/swpp_cjlk/issues/60
에서 좀 더 구체화되어서 여기서 해결하고 해결 하면 comment 하겠습니다
 해당 이슈는 close 하겟습니다
