### ISSUE TITLE
BACK-END 구현 필요 사항

### ISSUE THREAD

**Issue by hjcdg1** [hjcdg1/swpp_cjlk#48]
프론트 엔드를 개발하면서 백 엔드에서 구현이 필요한 부분을 일단 정리해봤습니다.
참고해주시고, 이것 먼저 구현해주시면 감사하겠습니다!

1. meetinglist/impending : state 값이 0, 2인 것만 보내주도록 수정 필요

2. meetinglist/recent : state 값이 0, 2인 것만 보내주도록 수정 필요

3. meetinglist/lead : 구현 필요 (lead_meeting 필드 활용)

4. meetinglist/join : 구현 필요 (state 값이 0, 1, 2, 3인 것만)

5. meetinglist/history : 구현 필요 (state 값이 4인 것만)

6. meetinglist/모임유형/page/페이지번호 : 구현 필요

7. 유저 정보 전체를 GET 하는 게 아니라 특정 유저 정보만 GET 할 수 있도록 구현 필요

8. Participate 정보 전체를 GET 하는 게 아니라 특정 Participate 정보만 GET 할 수 있도록 구현 필요

**Comment by ComputerMath** [comment]
https://github.com/hjcdg1/swpp_cjlk/pull/53   = >1,2,3,4,5,7,8 은 해당 PR에서 구현완료
https://github.com/hjcdg1/swpp_cjlk/pull/62   = > 6은 해당 PR에서 구현완료 했으니
해당 이슈는 닫습니다
