### ISSUE TITLE
5/2 Front End 역할 분담

### ISSUE THREAD

**Issue by hjcdg1** [hjcdg1/swpp_cjlk#6]
Design and Planning 문서에 작성한 Frontend Components에 근거하면 우리가 만들어야 할 리액트 컴포넌트들은 다음과 같이 그룹지을 수 있을 것 같다. 프론트 엔드 담당자가 세 명이므로 다음 중 세 개를 세 명이 맡고, 나머지 하나는 공동으로 작업하거나 자신의 작업이 조금 빨리 끝난 사람이 맡아주면 좋을 것 같다.

1. Log_in + Sign_up
2. Home + List
3. MyPage + New
4. Meeting + Left_sidebar + Right_sidebar

**Comment by kdw8573** [comment]
5/27일 기준으로 대충 페이지는 구현은 완료했고, 나머지는 기능 뿐임으로 이슈를 닫음
