### ISSUE TITLE
Participate Post Problem

### ISSUE THREAD

**Issue by hjcdg1** [hjcdg1/swpp_cjlk#60]
Participate 객체를 Post할 때 내가 참여한 모임의 개수를 체크하는 부분에 문제 제기.

내가 참여 중인 모임이 5개일 때, 

모임을 새로 만들면 Meeting 객체는 Post 되지만 

Participate 객체만 Post가 안 됨.

**Comment by ComputerMath** [comment]
확인했습니다 
backend에서 validate를 통해 추후 구현하겠습니다

**Comment by ComputerMath** [comment]
https://github.com/hjcdg1/swpp_cjlk/pull/64
구현 완료
